spring:
  jpa.hibernate:
    dialect: org.hibernate.MySQLDialect
    ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/campaign
    username: campaigntracker
    password: campaigntrackerpassword